# Generated by Django 4.2.6 on 2023-11-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCamper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('leadership_team', models.CharField(max_length=200)),
                ('module_status', models.CharField(max_length=200)),
                ('leave_left_hour', models.CharField(max_length=100)),
            ],
        ),
    ]
